# 1. Load packages
library(tidyverse)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

# A1. Import the first dataset (Lupinus polyphyllus)
#GBIF files are tab-separated
Lupinus <- read_tsv("data/Lupinus.csv")
dim(Lupinus)
glimpse(Lupinus)
names(Lupinus)
head(Lupinus)

# A2. Clean data (Lupinus polyphyllus)
lupinus_clean <- Lupinus %>% select(scientificName, decimalLatitude, decimalLongitude, year, basisOfRecord)
dim(lupinus_clean)
glimpse(lupinus_clean)
colSums(is.na(lupinus_clean))
lupinus_clean <- lupinus_clean %>% filter(!is.na(decimalLatitude), !is.na(decimalLongitude))
dim(lupinus_clean)
table(lupinus_clean$scientificName)
lupinus_clean <- lupinus_clean %>% filter(scientificName == "Lupinus polyphyllus Lindl.")
table(lupinus_clean$scientificName)
summary(lupinus_clean$decimalLatitude)
summary(lupinus_clean$decimalLongitude)
sum(duplicated(lupinus_clean))
lupinus_clean <- lupinus_clean %>% distinct()
sum(duplicated(lupinus_clean))
dim(lupinus_clean)
table(lupinus_clean$basisOfRecord)
summary(lupinus_clean$year)
write_csv(lupinus_clean, "data/lupinus_clean.csv")

# A3. Convert to spatial data (Lupinus polyphyllus)
Lupinus_poly <- lupinus_clean %>% st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)
class(Lupinus_poly)
dim(Lupinus_poly)

# A4. Map
Sweden <- ne_countries(country = "Sweden", scale = "medium", returnclass = "sf")
class(Sweden)
st_geometry_type(Sweden)
st_geometry_type(Lupinus_poly)
ggplot(data = Sweden) + geom_sf()
ggplot() + geom_sf(data = Sweden) + geom_sf(data = Lupinus_poly, size = 0.7, alpha = 0.4) + labs(title = "Distribution of Lupinus polyphyllum in Sweden", subtitle = "GBIF occurrence records") + theme_classic()
ggsave("figures/Lupinus_distribution_map.png", width = 8, height = 6, dpi = 300)

